export const MAKE_REQUEST = 'MAKE_REQUEST'
export const FAIL_REQUEST = 'FAIL_REQUEST'
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const GET_CATEGORY_NI_ITEMS = 'GET_CATEGORY_NI_ITEMS'
